### ISSUE TITLE
model variables

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#14]
A possibly incomplete list of problems with the model variables that we're requesting (or not requesting):
- [x] GFS: missing non-gust wind speed or components.
- [x] HRRR_ESRL: missing non-gust wind speed or components.
- [x] NAM: missing non-gust wind speed or components. What's the difference between `'Downward_Short-Wave_Radiation_Flux_surface'` and `'Downward_Short-Wave_Radiation_Flux_surface_Mixed_intervals_Average'`?
- [x] We should either get surface pressure for all models or for no models (missing from NDFD only).

I just pulled anything that seemed reasonably interesting in the proof of concept test, but now we need to do it right.

**Comment by MoonRaker** [comment]
The wind speed model variables have been addressed by adding the calc_wind function. 'Downward_Short-Wave_Radiation_Flux_surface_Mixed_intervals_Average' has been dropped in favor of 'Downward_Short-Wave_Radiation_Flux_surface'. Since the NDFD model doesn't provide pressure, pressure has been removed from all the models.
