### ISSUE TITLE
forecast class names

### ISSUE THREAD

**Issue by wholmgren** [MoonRaker/pvlib-python#5]
Trying to think about the names from an end user's perspective...

First, GFS/GFS_HIRES. Any reason not to make the 0.25 deg model the default? Then you'd instead have GFS_LORES, which would rarely be used. Or, maybe you have one GFS class for both but with a resolution keyword arg? Thinking out loud here.

NCEP should be renamed HRRR. Here, you could again have a keyword argument like `source` which can take values of `'ncep'` (default) or `'esrl'`. However, that sort of defeats the purpose of your class structure since the variable names are different. So maybe here you would want keep the two classes but with names like HRRR and HRRR_ESRL. I think I'd prefer HRRR to HRRR_NCEP since NCEP isn't specified for any of the other NCEP models. The HRRR_ESRL class could throw a warning about it being an experimental model.

**Comment by MoonRaker** [comment]
I have updated the classes to reflect the changes you suggested for the GFS model.  I just left the NCEP HRRR model as it is because that is how it is named on the THREDD server. I changed the name of the NOAA/GSD to GSD for the same reason as well. I am not sure what the ESRL model is or which one that refers too. I can't find any by that name explicitly listed in the catalogs. You may have to direct me specifically for that one.

**Comment by wholmgren** [comment]
So after talking about it, we've decided to rename:
- `NCEP` --> `HRRR` (since, like the RAP/NAM/GFS, the HRRR is also run by NCEP)
- `GSD` --> `HRRR_ESRL` (since GSD runs other models that we do not include)
